package b12x;

import neo4j.*;

import java.awt.CardLayout;
import java.awt.Component;
import java.nio.file.*;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Map;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KAEaton
 */
public class B12xGUI extends javax.swing.JFrame {

    /**
     * Creates new form B12xGUI
     */ 
    public B12xGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        neo4j = new javax.swing.JPanel();
        goButton = new javax.swing.JToggleButton();
        hlaSelectNeo4j = new javax.swing.JComboBox<>();
        instructions = new javax.swing.JLabel();
        mainCardPanel = new javax.swing.JPanel();
        jPanelEnterGfeA = new javax.swing.JPanel();
        hlaALabel2 = new javax.swing.JLabel();
        a00_WS = new javax.swing.JTextField();
        a01_5Prime = new javax.swing.JTextField();
        a02_Exon1 = new javax.swing.JTextField();
        a03_Intron1 = new javax.swing.JTextField();
        a04_Exon2 = new javax.swing.JTextField();
        a05_Intron2 = new javax.swing.JTextField();
        a06_Exon3 = new javax.swing.JTextField();
        a07_Intron3 = new javax.swing.JTextField();
        a08_Exon4 = new javax.swing.JTextField();
        a09_Intron4 = new javax.swing.JTextField();
        a10_Exon5 = new javax.swing.JTextField();
        a11_Intron5 = new javax.swing.JTextField();
        a12_Exon6 = new javax.swing.JTextField();
        a13_Intron6 = new javax.swing.JTextField();
        a14_Exon7 = new javax.swing.JTextField();
        a15_Intron7 = new javax.swing.JTextField();
        a16_Exon8 = new javax.swing.JTextField();
        a17_3Prime = new javax.swing.JTextField();
        jLabelAW = new javax.swing.JLabel();
        jLabelA5 = new javax.swing.JLabel();
        jLabelA3 = new javax.swing.JLabel();
        jLabelAE8 = new javax.swing.JLabel();
        jLabelAI7 = new javax.swing.JLabel();
        jLabelAE7 = new javax.swing.JLabel();
        jLabelAI6 = new javax.swing.JLabel();
        jLabelAE6 = new javax.swing.JLabel();
        jLabelAI5 = new javax.swing.JLabel();
        jLabelAE5 = new javax.swing.JLabel();
        jLabelAI4 = new javax.swing.JLabel();
        jLabelAE4 = new javax.swing.JLabel();
        jLabelAI3 = new javax.swing.JLabel();
        jLabelAI2 = new javax.swing.JLabel();
        jLabelAE2 = new javax.swing.JLabel();
        jLabelAI1 = new javax.swing.JLabel();
        jLabelAE1 = new javax.swing.JLabel();
        jLabelAE3 = new javax.swing.JLabel();
        jPanelC = new javax.swing.JPanel();
        jPanelEnterGfeC = new javax.swing.JPanel();
        hlaCLabel = new javax.swing.JLabel();
        c01_5Prime = new javax.swing.JTextField();
        c02_Exon1 = new javax.swing.JTextField();
        c03_Intron1 = new javax.swing.JTextField();
        c04_Exon2 = new javax.swing.JTextField();
        c05_Intron2 = new javax.swing.JTextField();
        c06_Exon3 = new javax.swing.JTextField();
        c07_Intron3 = new javax.swing.JTextField();
        c08_Exon4 = new javax.swing.JTextField();
        c09_Intron4 = new javax.swing.JTextField();
        c10_Exon5 = new javax.swing.JTextField();
        c11_Intron5 = new javax.swing.JTextField();
        c12_Exon6 = new javax.swing.JTextField();
        c13_Intron6 = new javax.swing.JTextField();
        c14_Exon7 = new javax.swing.JTextField();
        c15_Intron7 = new javax.swing.JTextField();
        c16_Exon8 = new javax.swing.JTextField();
        c17_3Prime = new javax.swing.JTextField();
        jLabelC5 = new javax.swing.JLabel();
        jLabelCE1 = new javax.swing.JLabel();
        jLabelCI1 = new javax.swing.JLabel();
        jLabelCE2 = new javax.swing.JLabel();
        jLabelCI2 = new javax.swing.JLabel();
        jLabelCE3 = new javax.swing.JLabel();
        jLabelCI3 = new javax.swing.JLabel();
        jLabelCE4 = new javax.swing.JLabel();
        jLabelCI4 = new javax.swing.JLabel();
        jLabelCE5 = new javax.swing.JLabel();
        jLabelCI5 = new javax.swing.JLabel();
        jLabelCE6 = new javax.swing.JLabel();
        jLabelCI6 = new javax.swing.JLabel();
        jLabelCE7 = new javax.swing.JLabel();
        jLabelCI7 = new javax.swing.JLabel();
        jLabelCE8 = new javax.swing.JLabel();
        jLabelC3 = new javax.swing.JLabel();
        jPanelEnterGfeB = new javax.swing.JPanel();
        hlaBLabel = new javax.swing.JLabel();
        b00_ws = new javax.swing.JTextField();
        b01_5Prime = new javax.swing.JTextField();
        b02_Exon1 = new javax.swing.JTextField();
        b03_Intron1 = new javax.swing.JTextField();
        b04_Exon2 = new javax.swing.JTextField();
        b05_Intron2 = new javax.swing.JTextField();
        b06_Exon3 = new javax.swing.JTextField();
        b07_Intron3 = new javax.swing.JTextField();
        b08_Exon4 = new javax.swing.JTextField();
        b09_Intron4 = new javax.swing.JTextField();
        b10_Exon5 = new javax.swing.JTextField();
        b11_Intron5 = new javax.swing.JTextField();
        b12_Exon6 = new javax.swing.JTextField();
        b13_Intron6 = new javax.swing.JTextField();
        b14_Exon7 = new javax.swing.JTextField();
        jLabelBW = new javax.swing.JLabel();
        jLabelB5 = new javax.swing.JLabel();
        jLabelBE1 = new javax.swing.JLabel();
        jLabelBI1 = new javax.swing.JLabel();
        jLabelBE2 = new javax.swing.JLabel();
        jLabelBI2 = new javax.swing.JLabel();
        jLabelBE3 = new javax.swing.JLabel();
        jLabelBI3 = new javax.swing.JLabel();
        jLabelBE4 = new javax.swing.JLabel();
        jLabelBI4 = new javax.swing.JLabel();
        jLabelBE5 = new javax.swing.JLabel();
        jLabelBI5 = new javax.swing.JLabel();
        jLabelBE6 = new javax.swing.JLabel();
        jLabelBI6 = new javax.swing.JLabel();
        jLabelE7 = new javax.swing.JLabel();
        neo4jUpdate = new javax.swing.JPanel();
        hlaSelectUpdate = new javax.swing.JComboBox<>();
        updateButton = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("B12x Search Generator");
        setAlwaysOnTop(true);

        neo4j.setName(""); // NOI18N

        goButton.setText("Go");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        hlaSelectNeo4j.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HLA-A", "HLA-B", "HLA-C" }));
        hlaSelectNeo4j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hlaSelectNeo4jActionPerformed(evt);
            }
        });

        instructions.setText("Enter in the terms you are looking for. (Zero is a valid term.)  Empty boxes function as wildcards.");

        mainCardPanel.setLayout(new java.awt.CardLayout());

        jPanelEnterGfeA.setName("jPanelEnterGfeA"); // NOI18N

        hlaALabel2.setText("HLA-A");

        a00_WS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a00_WS.setText("w");
        a00_WS.setName("00"); // NOI18N
        a00_WS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a00_WSActionPerformed(evt);
            }
        });

        a01_5Prime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a01_5Prime.setName("01"); // NOI18N

        a02_Exon1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a02_Exon1.setName("02"); // NOI18N

        a03_Intron1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a03_Intron1.setName("03"); // NOI18N

        a04_Exon2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a04_Exon2.setName("04"); // NOI18N

        a05_Intron2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a05_Intron2.setName("05"); // NOI18N

        a06_Exon3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a06_Exon3.setName("06"); // NOI18N

        a07_Intron3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a07_Intron3.setName("07"); // NOI18N

        a08_Exon4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a08_Exon4.setName("08"); // NOI18N

        a09_Intron4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a09_Intron4.setName("09"); // NOI18N

        a10_Exon5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a10_Exon5.setName("10"); // NOI18N

        a11_Intron5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a11_Intron5.setName("11"); // NOI18N

        a12_Exon6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a12_Exon6.setName("12"); // NOI18N

        a13_Intron6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a13_Intron6.setName("13"); // NOI18N

        a14_Exon7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a14_Exon7.setName("14"); // NOI18N

        a15_Intron7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a15_Intron7.setMaximumSize(new java.awt.Dimension(10, 26));
        a15_Intron7.setName("15"); // NOI18N

        a16_Exon8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a16_Exon8.setMaximumSize(new java.awt.Dimension(10, 26));
        a16_Exon8.setName("16"); // NOI18N

        a17_3Prime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a17_3Prime.setMaximumSize(new java.awt.Dimension(10, 26));
        a17_3Prime.setName("17"); // NOI18N

        TextIcon t1 = new TextIcon(jLabelAW, "Workshop Status", TextIcon.Layout.HORIZONTAL);
        RotatedIcon r1 = new RotatedIcon(t1, RotatedIcon.Rotate.DOWN);
        jLabelAW.setIcon( r1 );

        t1 = new TextIcon(jLabelA5, "5' UTR", TextIcon.Layout.HORIZONTAL);
        r1 = new RotatedIcon(t1, RotatedIcon.Rotate.DOWN);
        jLabelA5.setIcon( r1 );

        t1 = new TextIcon(jLabelA3, "3' UTR", TextIcon.Layout.HORIZONTAL);
        r1 = new RotatedIcon(t1, RotatedIcon.Rotate.DOWN);
        jLabelA3.setIcon( r1 );

        t1 = new TextIcon(jLabelAE8, "Exon 8", TextIcon.Layout.HORIZONTAL);
        r1 = new RotatedIcon(t1, RotatedIcon.Rotate.DOWN);
        jLabelAE8.setIcon( r1 );

        t1 = new TextIcon(jLabelAI7, "Intron 7", TextIcon.Layout.HORIZONTAL);
        r1 = new RotatedIcon(t1, RotatedIcon.Rotate.DOWN);
        jLabelAI7.setIcon( r1 );

        t1 = new TextIcon(jLabelAE7, "Exon 7", TextIcon.Layout.HORIZONTAL);
        r1 = new RotatedIcon(t1, RotatedIcon.Rotate.DOWN);
        jLabelAE7.setIcon( r1 );

        t1 = new TextIcon(jLabelAI6, "Intron 6", TextIcon.Layout.HORIZONTAL);
        r1 = new RotatedIcon(t1, RotatedIcon.Rotate.DOWN);
        jLabelAI6.setIcon( r1 );

        t1 = new TextIcon(jLabelAE6, "Exon 6", TextIcon.Layout.HORIZONTAL);
        r1 = new RotatedIcon(t1, RotatedIcon.Rotate.DOWN);
        jLabelAE6.setIcon( r1 );

        t1 = new TextIcon(jLabelAI5, "Intron 5", TextIcon.Layout.HORIZONTAL);
        r1 = new RotatedIcon(t1, RotatedIcon.Rotate.DOWN);
        jLabelAI5.setIcon( r1 );

        t1 = new TextIcon(jLabelAE5, "Exon 5", TextIcon.Layout.HORIZONTAL);
        r1 = new RotatedIcon(t1, RotatedIcon.Rotate.DOWN);
        jLabelAE5.setIcon( r1 );

        t1 = new TextIcon(jLabelAI4, "Intron 4", TextIcon.Layout.HORIZONTAL);
        r1 = new RotatedIcon(t1, RotatedIcon.Rotate.DOWN);
        jLabelAI4.setIcon( r1 );

        t1 = new TextIcon(jLabelAE4, "Exon 4", TextIcon.Layout.HORIZONTAL);
        r1 = new RotatedIcon(t1, RotatedIcon.Rotate.DOWN);
        jLabelAE4.setIcon( r1 );

        t1 = new TextIcon(jLabelAI3, "Intron 3", TextIcon.Layout.HORIZONTAL);
        r1 = new RotatedIcon(t1, RotatedIcon.Rotate.DOWN);
        jLabelAI3.setIcon( r1 );

        t1 = new TextIcon(jLabelAI2, "Intron 2", TextIcon.Layout.HORIZONTAL);
        r1 = new RotatedIcon(t1, RotatedIcon.Rotate.DOWN);
        jLabelAI2.setIcon( r1 );

        t1 = new TextIcon(jLabelAE2, "Exon 2", TextIcon.Layout.HORIZONTAL);
        r1 = new RotatedIcon(t1, RotatedIcon.Rotate.DOWN);
        jLabelAE2.setIcon( r1 );

        t1 = new TextIcon(jLabelAI1, "Intron 1", TextIcon.Layout.HORIZONTAL);
        r1 = new RotatedIcon(t1, RotatedIcon.Rotate.DOWN);
        jLabelAI1.setIcon( r1 );

        t1 = new TextIcon(jLabelAE1, "Exon 1", TextIcon.Layout.HORIZONTAL);
        r1 = new RotatedIcon(t1, RotatedIcon.Rotate.DOWN);
        jLabelAE1.setIcon( r1 );

        t1 = new TextIcon(jLabelAE3, "Exon 3", TextIcon.Layout.HORIZONTAL);
        r1 = new RotatedIcon(t1, RotatedIcon.Rotate.DOWN);
        jLabelAE3.setIcon( r1 );

        javax.swing.GroupLayout jPanelEnterGfeALayout = new javax.swing.GroupLayout(jPanelEnterGfeA);
        jPanelEnterGfeA.setLayout(jPanelEnterGfeALayout);
        jPanelEnterGfeALayout.setHorizontalGroup(
            jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hlaALabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a00_WS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelAW, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabelA5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a01_5Prime, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a02_Exon1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelAE1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabelAI1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a03_Intron1)))
                .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabelAE2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a04_Exon2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a05_Intron2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelAI2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a06_Exon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelAE3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a07_Intron3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelAI3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a08_Exon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelAE4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a09_Intron4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelAI4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a10_Exon5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelAE5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a11_Intron5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelAI5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a12_Exon6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelAE6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a13_Intron6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelAI6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a14_Exon7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelAE7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a15_Intron7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelAI7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a16_Exon8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelAE8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelA3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(a17_3Prime, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jPanelEnterGfeALayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {a01_5Prime, a02_Exon1, a03_Intron1, a04_Exon2, a05_Intron2, a06_Exon3, a07_Intron3, a08_Exon4, a09_Intron4, a10_Exon5, a11_Intron5, a12_Exon6, a13_Intron6, a14_Exon7, a15_Intron7, a16_Exon8, a17_3Prime});

        jPanelEnterGfeALayout.setVerticalGroup(
            jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addComponent(a00_WS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAW, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEnterGfeALayout.createSequentialGroup()
                        .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a01_5Prime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hlaALabel2)
                            .addComponent(a03_Intron1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a02_Exon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a04_Exon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a05_Intron2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a06_Exon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a07_Intron3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a08_Exon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a09_Intron4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a10_Exon5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a11_Intron5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a12_Exon6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a13_Intron6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a14_Exon7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a15_Intron7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a16_Exon8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a17_3Prime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEnterGfeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelA5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAE1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAI1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAE2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAI2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelA3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAE8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAI7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAE7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAI6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAE6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAI5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAE5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAI4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAE4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAI3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAE3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        mainCardPanel.add(jPanelEnterGfeA, "cardA");

        jPanelC.setName("jPanelEnterGFEC"); // NOI18N

        jPanelEnterGfeC.setName("jPanelEnterGfeC"); // NOI18N

        hlaCLabel.setText("HLA-Cw");

        c01_5Prime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c01_5Prime.setName("01"); // NOI18N

        c02_Exon1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c02_Exon1.setName("02"); // NOI18N

        c03_Intron1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c03_Intron1.setName("03"); // NOI18N

        c04_Exon2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c04_Exon2.setName("04"); // NOI18N

        c05_Intron2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c05_Intron2.setName("05"); // NOI18N

        c06_Exon3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c06_Exon3.setName("06"); // NOI18N

        c07_Intron3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c07_Intron3.setName("07"); // NOI18N

        c08_Exon4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c08_Exon4.setName("08"); // NOI18N

        c09_Intron4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c09_Intron4.setName("09"); // NOI18N

        c10_Exon5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c10_Exon5.setName("10"); // NOI18N

        c11_Intron5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c11_Intron5.setName("11"); // NOI18N

        c12_Exon6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c12_Exon6.setName("12"); // NOI18N

        c13_Intron6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c13_Intron6.setName("13"); // NOI18N

        c14_Exon7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c14_Exon7.setName("14"); // NOI18N

        c15_Intron7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c15_Intron7.setName("15"); // NOI18N

        c16_Exon8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c16_Exon8.setName("16"); // NOI18N

        c17_3Prime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c17_3Prime.setMaximumSize(new java.awt.Dimension(10, 26));
        c17_3Prime.setName("17"); // NOI18N

        TextIcon t1C = new TextIcon(jLabelC5, "5' UTR", TextIcon.Layout.HORIZONTAL);
        RotatedIcon r1C = new RotatedIcon(t1C, RotatedIcon.Rotate.DOWN);
        jLabelC5.setIcon( r1C );

        t1C = new TextIcon(jLabelCE1, "Exon 1", TextIcon.Layout.HORIZONTAL);
        r1C = new RotatedIcon(t1C, RotatedIcon.Rotate.DOWN);
        jLabelCE1.setIcon( r1C );

        t1C = new TextIcon(jLabelCI1, "Intron 1", TextIcon.Layout.HORIZONTAL);
        r1C = new RotatedIcon(t1C, RotatedIcon.Rotate.DOWN);
        jLabelCI1.setIcon( r1C );

        t1C = new TextIcon(jLabelCE2, "Exon 2", TextIcon.Layout.HORIZONTAL);
        r1C = new RotatedIcon(t1C, RotatedIcon.Rotate.DOWN);
        jLabelCE2.setIcon( r1C );

        t1C = new TextIcon(jLabelCI2, "Intron 2", TextIcon.Layout.HORIZONTAL);
        r1C = new RotatedIcon(t1C, RotatedIcon.Rotate.DOWN);
        jLabelCI2.setIcon( r1C );

        t1C = new TextIcon(jLabelCE3, "Exon 3", TextIcon.Layout.HORIZONTAL);
        r1C = new RotatedIcon(t1C, RotatedIcon.Rotate.DOWN);
        jLabelCE3.setIcon( r1C );

        t1C = new TextIcon(jLabelCI3, "Intron 3", TextIcon.Layout.HORIZONTAL);
        r1C = new RotatedIcon(t1C, RotatedIcon.Rotate.DOWN);
        jLabelCI3.setIcon( r1C );

        t1C = new TextIcon(jLabelCE4, "Exon 4", TextIcon.Layout.HORIZONTAL);
        r1C = new RotatedIcon(t1C, RotatedIcon.Rotate.DOWN);
        jLabelCE4.setIcon( r1C );

        t1C = new TextIcon(jLabelCI4, "Intron 4", TextIcon.Layout.HORIZONTAL);
        r1C = new RotatedIcon(t1C, RotatedIcon.Rotate.DOWN);
        jLabelCI4.setIcon( r1C );

        t1C = new TextIcon(jLabelCE5, "Exon 5", TextIcon.Layout.HORIZONTAL);
        r1C = new RotatedIcon(t1C, RotatedIcon.Rotate.DOWN);
        jLabelCE5.setIcon( r1C );

        t1C = new TextIcon(jLabelCI5, "Intron 5", TextIcon.Layout.HORIZONTAL);
        r1C = new RotatedIcon(t1C, RotatedIcon.Rotate.DOWN);
        jLabelCI5.setIcon( r1C );

        t1C = new TextIcon(jLabelCE6, "Exon 6", TextIcon.Layout.HORIZONTAL);
        r1C = new RotatedIcon(t1C, RotatedIcon.Rotate.DOWN);
        jLabelCE6.setIcon( r1C );

        t1C = new TextIcon(jLabelCI6, "Intron 6", TextIcon.Layout.HORIZONTAL);
        r1C = new RotatedIcon(t1C, RotatedIcon.Rotate.DOWN);
        jLabelCI6.setIcon( r1C );

        t1C = new TextIcon(jLabelCE7, "Exon 7", TextIcon.Layout.HORIZONTAL);
        r1C = new RotatedIcon(t1C, RotatedIcon.Rotate.DOWN);
        jLabelCE7.setIcon( r1C );

        t1C = new TextIcon(jLabelCI7, "Intron 7", TextIcon.Layout.HORIZONTAL);
        r1C = new RotatedIcon(t1C, RotatedIcon.Rotate.DOWN);
        jLabelCI7.setIcon( r1C );

        t1C = new TextIcon(jLabelCE8, "Exon 8", TextIcon.Layout.HORIZONTAL);
        r1C = new RotatedIcon(t1C, RotatedIcon.Rotate.DOWN);
        jLabelCE8.setIcon( r1C );

        t1C = new TextIcon(jLabelC3, "3' UTR", TextIcon.Layout.HORIZONTAL);
        r1C = new RotatedIcon(t1C, RotatedIcon.Rotate.DOWN);
        jLabelC3.setIcon( r1C );

        javax.swing.GroupLayout jPanelEnterGfeCLayout = new javax.swing.GroupLayout(jPanelEnterGfeC);
        jPanelEnterGfeC.setLayout(jPanelEnterGfeCLayout);
        jPanelEnterGfeCLayout.setHorizontalGroup(
            jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnterGfeCLayout.createSequentialGroup()
                .addComponent(hlaCLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c01_5Prime, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelC5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c02_Exon1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCE1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c03_Intron1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCI1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c04_Exon2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCE2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c05_Intron2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCI2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c06_Exon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCE3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c07_Intron3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCI3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c08_Exon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCE4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c09_Intron4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCI4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c10_Exon5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCE5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c11_Intron5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCI5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c12_Exon6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCE6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c13_Intron6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCI6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c14_Exon7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCE7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c15_Intron7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCI7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c16_Exon8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCE8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c17_3Prime, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelC3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelEnterGfeCLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {c01_5Prime, c02_Exon1, c03_Intron1, c04_Exon2, c05_Intron2, c06_Exon3, c07_Intron3, c08_Exon4, c09_Intron4, c10_Exon5, c11_Intron5, c12_Exon6, c13_Intron6, c14_Exon7, c15_Intron7, c16_Exon8, c17_3Prime});

        jPanelEnterGfeCLayout.setVerticalGroup(
            jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnterGfeCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c01_5Prime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hlaCLabel)
                    .addComponent(c05_Intron2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c04_Exon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c06_Exon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c07_Intron3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c08_Exon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c09_Intron4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c10_Exon5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c11_Intron5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c12_Exon6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c13_Intron6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c14_Exon7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c15_Intron7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c16_Exon8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c17_3Prime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c02_Exon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c03_Intron1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelC5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCE1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCI1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCE2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCI2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCI3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelC3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCE8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCI7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCE7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCI6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCE6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCI5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCE5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCI4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCE4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCE3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCLayout = new javax.swing.GroupLayout(jPanelC);
        jPanelC.setLayout(jPanelCLayout);
        jPanelCLayout.setHorizontalGroup(
            jPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEnterGfeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );
        jPanelCLayout.setVerticalGroup(
            jPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEnterGfeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        mainCardPanel.add(jPanelC, "cardC");

        jPanelEnterGfeB.setName("jPanelEnterGfeB"); // NOI18N

        hlaBLabel.setText("HLA-B");

        b00_ws.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b00_ws.setText("w");
        b00_ws.setName("00"); // NOI18N

        b01_5Prime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b01_5Prime.setName("01"); // NOI18N

        b02_Exon1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b02_Exon1.setName("02"); // NOI18N

        b03_Intron1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b03_Intron1.setName("03"); // NOI18N

        b04_Exon2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b04_Exon2.setName("04"); // NOI18N

        b05_Intron2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b05_Intron2.setName("05"); // NOI18N

        b06_Exon3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b06_Exon3.setName("06"); // NOI18N

        b07_Intron3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b07_Intron3.setName("07"); // NOI18N

        b08_Exon4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b08_Exon4.setName("08"); // NOI18N

        b09_Intron4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b09_Intron4.setName("09"); // NOI18N

        b10_Exon5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b10_Exon5.setName("10"); // NOI18N

        b11_Intron5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b11_Intron5.setName("11"); // NOI18N

        b12_Exon6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b12_Exon6.setName("12"); // NOI18N

        b13_Intron6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b13_Intron6.setName("13"); // NOI18N

        b14_Exon7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b14_Exon7.setName("14"); // NOI18N

        TextIcon t1B = new TextIcon(jLabelBW, "Workshop Status", TextIcon.Layout.HORIZONTAL);
        RotatedIcon r1B = new RotatedIcon(t1B, RotatedIcon.Rotate.DOWN);
        jLabelBW.setIcon( r1B );

        t1B = new TextIcon(jLabelB5, "5' UTR", TextIcon.Layout.HORIZONTAL);
        r1B = new RotatedIcon(t1B, RotatedIcon.Rotate.DOWN);
        jLabelB5.setIcon( r1B );

        t1B = new TextIcon(jLabelBE1, "Exon 1", TextIcon.Layout.HORIZONTAL);
        r1B = new RotatedIcon(t1B, RotatedIcon.Rotate.DOWN);
        jLabelBE1.setIcon( r1B );

        t1B = new TextIcon(jLabelBI1, "Intron 1", TextIcon.Layout.HORIZONTAL);
        r1B = new RotatedIcon(t1B, RotatedIcon.Rotate.DOWN);
        jLabelBI1.setIcon( r1B );

        t1B = new TextIcon(jLabelBE2, "Exon 2", TextIcon.Layout.HORIZONTAL);
        r1B = new RotatedIcon(t1B, RotatedIcon.Rotate.DOWN);
        jLabelBE2.setIcon( r1B );

        t1B = new TextIcon(jLabelBI2, "Intron 2", TextIcon.Layout.HORIZONTAL);
        r1B = new RotatedIcon(t1B, RotatedIcon.Rotate.DOWN);
        jLabelBI2.setIcon( r1B );

        t1B = new TextIcon(jLabelBE3, "Exon 3", TextIcon.Layout.HORIZONTAL);
        r1B = new RotatedIcon(t1B, RotatedIcon.Rotate.DOWN);
        jLabelBE3.setIcon( r1B );

        t1B = new TextIcon(jLabelBI3, "Intron 3", TextIcon.Layout.HORIZONTAL);
        r1B = new RotatedIcon(t1B, RotatedIcon.Rotate.DOWN);
        jLabelBI3.setIcon( r1B );

        t1B = new TextIcon(jLabelBE4, "Exon 4", TextIcon.Layout.HORIZONTAL);
        r1B = new RotatedIcon(t1B, RotatedIcon.Rotate.DOWN);
        jLabelBE4.setIcon( r1B );

        t1B = new TextIcon(jLabelBI4, "Intron 4", TextIcon.Layout.HORIZONTAL);
        r1B = new RotatedIcon(t1B, RotatedIcon.Rotate.DOWN);
        jLabelBI4.setIcon( r1B );

        t1B = new TextIcon(jLabelBE5, "Exon 5", TextIcon.Layout.HORIZONTAL);
        r1B = new RotatedIcon(t1B, RotatedIcon.Rotate.DOWN);
        jLabelBE5.setIcon( r1B );

        t1B = new TextIcon(jLabelBI5, "Intron 5", TextIcon.Layout.HORIZONTAL);
        r1B = new RotatedIcon(t1B, RotatedIcon.Rotate.DOWN);
        jLabelBI5.setIcon( r1B );

        t1B = new TextIcon(jLabelBE6, "Exon 6", TextIcon.Layout.HORIZONTAL);
        r1B = new RotatedIcon(t1B, RotatedIcon.Rotate.DOWN);
        jLabelBE6.setIcon( r1B );

        t1B = new TextIcon(jLabelBI6, "Intron 6", TextIcon.Layout.HORIZONTAL);
        r1B = new RotatedIcon(t1B, RotatedIcon.Rotate.DOWN);
        jLabelBI6.setIcon( r1B );

        t1B = new TextIcon(jLabelE7, "Exon 7", TextIcon.Layout.HORIZONTAL);
        r1B = new RotatedIcon(t1B, RotatedIcon.Rotate.DOWN);
        jLabelE7.setIcon( r1B );

        javax.swing.GroupLayout jPanelEnterGfeBLayout = new javax.swing.GroupLayout(jPanelEnterGfeB);
        jPanelEnterGfeB.setLayout(jPanelEnterGfeBLayout);
        jPanelEnterGfeBLayout.setHorizontalGroup(
            jPanelEnterGfeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnterGfeBLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hlaBLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b00_ws, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeBLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelBW, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanelEnterGfeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnterGfeBLayout.createSequentialGroup()
                        .addComponent(b01_5Prime, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanelEnterGfeBLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelB5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanelEnterGfeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b02_Exon1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeBLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelBE1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b03_Intron1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeBLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelBI1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b04_Exon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeBLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelBE2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b05_Intron2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeBLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelBI2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b06_Exon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeBLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelBE3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b07_Intron3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeBLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelBI3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b08_Exon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeBLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelBE4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b09_Intron4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeBLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelBI4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b10_Exon5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeBLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelBE5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b11_Intron5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeBLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelBI5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b12_Exon6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeBLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelBE6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b13_Intron6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnterGfeBLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelBI6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnterGfeBLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelE7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(b14_Exon7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(716, 716, 716))
        );

        jPanelEnterGfeBLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {b01_5Prime, b02_Exon1, b03_Intron1, b04_Exon2, b05_Intron2, b06_Exon3, b07_Intron3, b08_Exon4, b09_Intron4, b10_Exon5, b11_Intron5, b12_Exon6, b13_Intron6, b14_Exon7});

        jPanelEnterGfeBLayout.setVerticalGroup(
            jPanelEnterGfeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnterGfeBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnterGfeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hlaBLabel)
                    .addComponent(b01_5Prime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b02_Exon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b03_Intron1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b04_Exon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b05_Intron2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b06_Exon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b07_Intron3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b08_Exon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b09_Intron4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b10_Exon5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b11_Intron5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b12_Exon6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b13_Intron6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b14_Exon7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b00_ws, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnterGfeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnterGfeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelBI6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addComponent(jLabelBE6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBI5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBE5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBI4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBE4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBI3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBE3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBI2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBE2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBI1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBE1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelE7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelB5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelBW, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        mainCardPanel.add(jPanelEnterGfeB, "cardB");

        javax.swing.GroupLayout neo4jLayout = new javax.swing.GroupLayout(neo4j);
        neo4j.setLayout(neo4jLayout);
        neo4jLayout.setHorizontalGroup(
            neo4jLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, neo4jLayout.createSequentialGroup()
                .addGroup(neo4jLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, neo4jLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(mainCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, neo4jLayout.createSequentialGroup()
                        .addGroup(neo4jLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(neo4jLayout.createSequentialGroup()
                                .addGap(383, 383, 383)
                                .addComponent(goButton))
                            .addGroup(neo4jLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(hlaSelectNeo4j, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        neo4jLayout.setVerticalGroup(
            neo4jLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, neo4jLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(neo4jLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hlaSelectNeo4j, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instructions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(goButton)
                .addGap(52, 52, 52))
        );

        jTabbedPane2.addTab("Neo4j GFE Search", neo4j);

        hlaSelectUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HLA-A", "HLA-B", "HLA-C" }));

        updateButton.setText("Update Neo4j Records");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("The allele data is automatically updated if the data is more than 30 days old when you run the GFE search. ");

        jLabel3.setText("This tool is for forcing a data update before that time is up. ");

        javax.swing.GroupLayout neo4jUpdateLayout = new javax.swing.GroupLayout(neo4jUpdate);
        neo4jUpdate.setLayout(neo4jUpdateLayout);
        neo4jUpdateLayout.setHorizontalGroup(
            neo4jUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(neo4jUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(neo4jUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(neo4jUpdateLayout.createSequentialGroup()
                        .addComponent(hlaSelectUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(updateButton))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(374, Short.MAX_VALUE))
        );
        neo4jUpdateLayout.setVerticalGroup(
            neo4jUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(neo4jUpdateLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(neo4jUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hlaSelectUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton))
                .addContainerGap(339, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Neo4j Update", neo4jUpdate);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
            String locus = hlaSelectUpdate.getSelectedItem().toString();
            String neo4jLocation = "";
            Path path = Paths.get(System.getProperty("user.home") 
                    + System.getProperty("file.separator") + "Documents" 
                    + System.getProperty("file.separator") 
                    + "neo4j_" + locus + "_Download.csv");

            Neo4j neo4j = new Neo4j(locus, path);
            neo4j.dataUpdate();
        } catch (Exception ex) {
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void a00_WSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a00_WSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a00_WSActionPerformed

    private void hlaSelectNeo4jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hlaSelectNeo4jActionPerformed
        String selectedLocus = (String)hlaSelectNeo4j.getSelectedItem();
        CardLayout card = (CardLayout)mainCardPanel.getLayout();
        switch (selectedLocus) {
            case "HLA-A":
            card.show(mainCardPanel, "cardA");
            System.out.println(selectedLocus);
            break;
            case "HLA-B":
            card.show(mainCardPanel, "cardB");
            System.out.println(selectedLocus);
            break;
            case "HLA-C":
            card.show(mainCardPanel, "cardC");
            System.out.println(selectedLocus);
            break;
        }
    }//GEN-LAST:event_hlaSelectNeo4jActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        try {
            String locus = hlaSelectNeo4j.getSelectedItem().toString();
            String parsedLocus = LocusNameParser.parseLocus(locus);
            String neo4jLocation = "";
            Path dataPath = Paths.get(System.getProperty("user.home")
                + System.getProperty("file.separator") + "Documents"
                + System.getProperty("file.separator") + "BSGData"
                + System.getProperty("file.separator")
                + "neo4j_" + locus + "_Download.csv");

            //            Neo4j neo4j = new Neo4j(locus, dataPath);
            //            neo4j.fetchData();

            System.out.println(parsedLocus);

            //            String locusARegex = "^HLA-Aw(\\d+)-(\\d+)-(\\d+)-(\\d+)-(\\d+)"
            //            + "-(\\d+)-(\\d+)-(\\d+)-(\\d+)-(\\d+)-(\\d+)-(\\d+)-(\\d+)-(\\d+)"
            //            + "-(\\d+)-(\\d+)-(\\d+)$";

            String panelName = "jPanelEnterGFE" + parsedLocus;
            Component currentGfePanel = jPanelEnterGfeB;
            String currentRegex = "^" + locus;
            String finalRegex;
            ArrayList<JTextField> typeFields = new ArrayList();

            // Find the right GFE entry panel

            for (Component component : mainCardPanel.getComponents()) {
                if (component.getName().equals(panelName)){
                    currentGfePanel = component;
                }
            }

            // Find the text fields and add to array
            //            for (Component component : jPanelEnterGfeA.getComponents()) {
                for (Component component : ((JPanel)currentGfePanel).getComponents()) {
                    if (component instanceof JTextField){
                        typeFields.add((JTextField)component);
                    }
                }

                // Sort the array list by name to check/keep the order
                Collections.sort(typeFields, Comparator.comparing(JTextField::getName));

                // Special rules for textfield 00
                if (typeFields.get(0).getText().isEmpty()){
                    currentRegex = currentRegex.concat("w");
                } else {
                    currentRegex = currentRegex.concat(typeFields.get(0).getText());
                }

                // For each textfield add regex or specified term to currentRegex
                for (int i = 1; i < typeFields.size(); i++){
                    //                System.out.println(((JTextField)typeFields.get(i)).getName());

                    if (typeFields.get(i).getText().isEmpty()){
                        currentRegex = currentRegex.concat("(\\d+)-");
                    } else {
                        currentRegex = currentRegex.concat(typeFields.get(i).getText() + "-");
                    }
                }

                // Check for extraneous dash at the end and close regex
                if (currentRegex.matches("^.+-$")){
                    finalRegex = currentRegex.substring(0, (currentRegex.length() - 1));//.concat("$");
                } else {
                    finalRegex = currentRegex;//.concat("$");
                }

                System.out.println("Gui running " + locus);
                System.out.println("Final Regex " + finalRegex);

            } catch (Exception ex) {
                System.out.println(ex);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_goButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B12xGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B12xGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B12xGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B12xGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B12xGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a00_WS;
    private javax.swing.JTextField a01_5Prime;
    private javax.swing.JTextField a02_Exon1;
    private javax.swing.JTextField a03_Intron1;
    private javax.swing.JTextField a04_Exon2;
    private javax.swing.JTextField a05_Intron2;
    private javax.swing.JTextField a06_Exon3;
    private javax.swing.JTextField a07_Intron3;
    private javax.swing.JTextField a08_Exon4;
    private javax.swing.JTextField a09_Intron4;
    private javax.swing.JTextField a10_Exon5;
    private javax.swing.JTextField a11_Intron5;
    private javax.swing.JTextField a12_Exon6;
    private javax.swing.JTextField a13_Intron6;
    private javax.swing.JTextField a14_Exon7;
    private javax.swing.JTextField a15_Intron7;
    private javax.swing.JTextField a16_Exon8;
    private javax.swing.JTextField a17_3Prime;
    private javax.swing.JTextField b00_ws;
    private javax.swing.JTextField b01_5Prime;
    private javax.swing.JTextField b02_Exon1;
    private javax.swing.JTextField b03_Intron1;
    private javax.swing.JTextField b04_Exon2;
    private javax.swing.JTextField b05_Intron2;
    private javax.swing.JTextField b06_Exon3;
    private javax.swing.JTextField b07_Intron3;
    private javax.swing.JTextField b08_Exon4;
    private javax.swing.JTextField b09_Intron4;
    private javax.swing.JTextField b10_Exon5;
    private javax.swing.JTextField b11_Intron5;
    private javax.swing.JTextField b12_Exon6;
    private javax.swing.JTextField b13_Intron6;
    private javax.swing.JTextField b14_Exon7;
    private javax.swing.JTextField c01_5Prime;
    private javax.swing.JTextField c02_Exon1;
    private javax.swing.JTextField c03_Intron1;
    private javax.swing.JTextField c04_Exon2;
    private javax.swing.JTextField c05_Intron2;
    private javax.swing.JTextField c06_Exon3;
    private javax.swing.JTextField c07_Intron3;
    private javax.swing.JTextField c08_Exon4;
    private javax.swing.JTextField c09_Intron4;
    private javax.swing.JTextField c10_Exon5;
    private javax.swing.JTextField c11_Intron5;
    private javax.swing.JTextField c12_Exon6;
    private javax.swing.JTextField c13_Intron6;
    private javax.swing.JTextField c14_Exon7;
    private javax.swing.JTextField c15_Intron7;
    private javax.swing.JTextField c16_Exon8;
    private javax.swing.JTextField c17_3Prime;
    private javax.swing.JToggleButton goButton;
    private javax.swing.JLabel hlaALabel2;
    private javax.swing.JLabel hlaBLabel;
    private javax.swing.JLabel hlaCLabel;
    private javax.swing.JComboBox<String> hlaSelectNeo4j;
    private javax.swing.JComboBox<String> hlaSelectUpdate;
    private javax.swing.JLabel instructions;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelA3;
    private javax.swing.JLabel jLabelA5;
    private javax.swing.JLabel jLabelAE1;
    private javax.swing.JLabel jLabelAE2;
    private javax.swing.JLabel jLabelAE3;
    private javax.swing.JLabel jLabelAE4;
    private javax.swing.JLabel jLabelAE5;
    private javax.swing.JLabel jLabelAE6;
    private javax.swing.JLabel jLabelAE7;
    private javax.swing.JLabel jLabelAE8;
    private javax.swing.JLabel jLabelAI1;
    private javax.swing.JLabel jLabelAI2;
    private javax.swing.JLabel jLabelAI3;
    private javax.swing.JLabel jLabelAI4;
    private javax.swing.JLabel jLabelAI5;
    private javax.swing.JLabel jLabelAI6;
    private javax.swing.JLabel jLabelAI7;
    private javax.swing.JLabel jLabelAW;
    private javax.swing.JLabel jLabelB5;
    private javax.swing.JLabel jLabelBE1;
    private javax.swing.JLabel jLabelBE2;
    private javax.swing.JLabel jLabelBE3;
    private javax.swing.JLabel jLabelBE4;
    private javax.swing.JLabel jLabelBE5;
    private javax.swing.JLabel jLabelBE6;
    private javax.swing.JLabel jLabelBI1;
    private javax.swing.JLabel jLabelBI2;
    private javax.swing.JLabel jLabelBI3;
    private javax.swing.JLabel jLabelBI4;
    private javax.swing.JLabel jLabelBI5;
    private javax.swing.JLabel jLabelBI6;
    private javax.swing.JLabel jLabelBW;
    private javax.swing.JLabel jLabelC3;
    private javax.swing.JLabel jLabelC5;
    private javax.swing.JLabel jLabelCE1;
    private javax.swing.JLabel jLabelCE2;
    private javax.swing.JLabel jLabelCE3;
    private javax.swing.JLabel jLabelCE4;
    private javax.swing.JLabel jLabelCE5;
    private javax.swing.JLabel jLabelCE6;
    private javax.swing.JLabel jLabelCE7;
    private javax.swing.JLabel jLabelCE8;
    private javax.swing.JLabel jLabelCI1;
    private javax.swing.JLabel jLabelCI2;
    private javax.swing.JLabel jLabelCI3;
    private javax.swing.JLabel jLabelCI4;
    private javax.swing.JLabel jLabelCI5;
    private javax.swing.JLabel jLabelCI6;
    private javax.swing.JLabel jLabelCI7;
    private javax.swing.JLabel jLabelE7;
    private javax.swing.JPanel jPanelC;
    private javax.swing.JPanel jPanelEnterGfeA;
    private javax.swing.JPanel jPanelEnterGfeB;
    private javax.swing.JPanel jPanelEnterGfeC;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel mainCardPanel;
    private javax.swing.JPanel neo4j;
    private javax.swing.JPanel neo4jUpdate;
    private javax.swing.JToggleButton updateButton;
    // End of variables declaration//GEN-END:variables

}
